jazzband/django-rest-knox

- knox/settings.py
- knox/views.py
- knox_project/urls.py
- knox_project/views.py
- tests/tests.py
- add a test url/view "api-root"
- add a test for #20 where an invalid token length leads to a 500 response, but could't not reproduce it
- revert 73aef41 as I think it makes rest-knox less flexible, see my comment here: 73aef41#commitcomment-20145730
> Test for invalid token length

- CHANGELOG.rst
- docs/auth.md
- docs/changes.md
- docs/settings.md
- knox/auth.py
- setup.py
- tests/tests.py
- closes #25 Docs don't mention usage of knox in DEFAULT_AUTHENTICATION_CLASSES
- closes #20￼ Error when user send token is not valid length
> Bugfix release 2.2.2

- knox/views.py
If the custom `UserSerializer` has hyperlinked fields, it is necessary to have the request in the serializer context. This is provided "for free" by `GenericAPIView`'s `.get_serializer_context()`.
This is my first contribution to this project, so I hope everything is alright. =)
> Add context to UserSerializer

- docs/auth.md
- docs/settings.md
There seems to be a small syntax error with the settings example where the documentation recommends assigning to a literal string. This commit just removes the quotes to make it a variable name.
> Fix SyntaxError in settings example in documentation

- knox/crypto.py
Follows suggestion in pyOpenSSL changelog https://github.com/pyca/pyopenssl/blob/1eac0e8f9b3829c5401151fabb3f78453ad772a4/CHANGELOG.rst#backward-incompatible-changes-1
> Use os.urandom instead of OpenSSL.rand.bytes

- CHANGELOG.rst
- docs/changes.md
- setup.py
use hmac.compare_digest instead of == for comparing hashes for more security
> release notes for 3.1.1 bugfix release

- knox/auth.py
- knox/crypto.py
- tests/tests.py
This fixes an edge case that only occurs when valid token is extended.
If I take a token a valid token (even length) and add a character to it, this will make an invalid, odd-length token. This token will pass the [first check][0], because the token is sliced to the correct length in the filter statement, but then an error occurs in [knox.crypto][1].
Fixes #46 
[0]: https://github.com/James1345/django-rest-knox/blob/45be9d1fc0c7963954803a3b01425f6b540f8673/knox/auth.py#L64
[1]: https://github.com/James1345/django-rest-knox/blob/45be9d1fc0c7963954803a3b01425f6b540f8673/knox/crypto.py#L29-L30
> Add fix and test for binascii.Error Odd-Length

- knox/views.py
This pull request refactors the three Knox views to subclass `APIView` instead of `GenericAPIView`, which resolves #94. 
The only `GenericAPIView` functionality currently being used is `get_serializer_context()` in `LoginView`, which is a very simple function that creates a context dictionary with no other `GenericAPIView` dependencies. Its functionality has been replicated by creating the context dictionary directly in `LoginView`.
> Refactor views to subclass APIView instead of GenericAPIView

- docs/settings.md
- knox/auth.py
- knox/settings.py
- knox_project/settings.py
- tests/tests.py
- tox.ini
Implement enhancement https://github.com/James1345/django-rest-knox/issues/37
> Add AUTO_REFRESH setting

- docs/changes.md
- docs/index.md
- docs/settings.md
- knox/settings.py
- knox/views.py
- tests/tests.py
@belugame This is what I got thus far. I have verified the functionality manually -- it works but I am having trouble with the test not respecting the overridden `TOKEN_LIMIT`, thus the test fails -- I figured the default settings value should be `None` since this option does come with a performance cost and is not needed by everyone.
I mean I could just set `knox_settings.TOKEN_LIMIT = 10` inside the testcase but.. is that the correct way?
Related: https://github.com/James1345/django-rest-knox/issues/108
> add: optional token limit per user object

- docs/settings.md
- knox/auth.py
- knox/settings.py
- tests/tests.py
> Make auth header prefix configurable

- README.rst
- docker-run-tests.sh
This was handy to run the all matrix of tests locally and could help others.
On the other hand I would totally understand if you don't like the Docker dependency or don't want to maintain something like this ✌️
> Add docker support to run the tests

- knox_project/urls.py
`path` will trigger a warning when used with a regex while
`re_path` is what should be used instead.
> Fix #128 Replace path with re_path in test urls

- CHANGELOG.md
- docs/changes.md
- docs/views.md
- knox/views.py
- setup.py
We need the following changes to reuse LoginView default post method instead of overriding it:
- make the context passed to the UserSerializer configurable as our serializer requires more data
- make the TTL of the AuthToken configurable instead of the default as we want to use a different TTL depending on the authentication class used
While at it create the context only if needed.
> Make the LoginView more flexible

- CHANGELOG.md
- docs/changes.md
- docs/views.md
- knox/views.py
So that's easily overridable when hosting more than one instance
of LoginView in the same project.
> Make the user serializer configurable for LoginView

- .isort.cfg
- knox/admin.py
- knox/auth.py
- knox/crypto.py
- knox/migrations/0001_initial.py
- knox/migrations/0002_auto_20150916_1425.py
- knox/migrations/0003_auto_20150916_1526.py
- knox/serializers.py
- knox/settings.py
- knox/views.py
- knox_project/views.py
- setup.py
- tests/tests.py
- tox.ini
Hello, 
Adds isort to testenv and sorts all imports. Closes https://github.com/James1345/django-rest-knox/issues/154 :cat2:
We might want to add some extra rules, personally I run these in my projects:
```
[isort]
combine_as_imports = true
default_section = THIRDPARTY
include_trailing_comma = true
known_first_party = django
line_length = 79
multi_line_output = 5
not_skip = __init__.py
```
Also, this does not test the imports in `tests/`. Let me know if that feels like something you might want.
Cheers mates
> fixes #154 -- adds isort

- CHANGELOG.md
- docs/settings.md
- docs/views.md
- knox/settings.py
- knox/views.py
- setup.py
- tests/tests.py
Replaces #179 
Fixes #171 
Fixes #178 
- Now expiry format defaults to whatever is used Django REST framework
- This behavior can be overriden via `EXPIRY_DATETIME_FORMAT` setting
- fully customizable expiry format via `format_expiry_datetime`
- fully customizable response payload via `get_post_response_data`
> Add setting for expiry format, add helper methods in login view

- .travis.yml
- setup.py
- tox.ini
Python 3.4 is end-of-life (https://www.python.org/downloads/release/python-340/), we can stop supporting it.
Some builds (https://travis-ci.org/James1345/django-rest-knox/jobs/647661512, https://travis-ci.org/James1345/django-rest-knox/jobs/647660925) are now failing because `PyYAML requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*' but the running Python is 3.4.8`
> Stop testing with Python 3.4

- .travis.yml
- knox/auth.py
- setup.py
- tox.ini
I was triggered to look into this by https://github.com/James1345/django-rest-knox/issues/194. It looks like the reporter of that issue has had some kind of misconfiguration, and that issue can be closed. 
But it does look like the definition of `User` is superfluous here.
> Remove unused User definition

- knox/auth.py
- tests/tests.py
The current code in authenticate() seems to try to raise
AuthenticationFailed if the authentication header is just one word:
if not auth or auth[0].lower() != prefix.lower():
return None
if len(auth) == 1:
msg = _('Invalid token header. No credentials provided.')
raise exceptions.AuthenticationFailed(msg)
However, if `auth` has just one item, `auth[0].lower()` is not likely
to equal the prefix. So probably we'll just return None.
This commit tries to fix that by testing
`auth[0].lower() != prefix.lower()` only after we've checked that we
received the correct number of words in the authentication header.
> Raise AuthenticationFailed for one all one word headers, not just "Token"

- README.md
- knox/auth.py
```
RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
```
See: https://docs.djangoproject.com/en/3.0/_modules/django/utils/translation/
> fix django warnings - ugettext_lazy is deprecated

- README.md
I believe tokens are stored in a hashed form, not an encrypted form in the database. This change updates the README to reflect this distinction.
> correct language about token hashing

- knox/signals.py
Recently, Django has started throwing some deprecation warnings.  `Signal` no longer has a `providing_args` parameter.
```
/lib/python3.8/site-packages/knox/signals.py:3: RemovedInDjango40Warning: The providing_args argument is deprecated. As it is purely documentational, it has no replacement. If you rely on this argument as documentation, you can move the text to a code comment or docstring.
token_expired = django.dispatch.Signal(providing_args=["username", "source"])
```
Closes #232
> Fix Django deprecation warning about Signals

- docs/settings.md
TOKEN_LIMIT_PER_USER does not expire older tokens, it just denies to creating a new token.
> docu: clearify behavior of TOKEN_LIMIT_PER_USER

- docs/installation.md
- docs/settings.md
- knox/crypto.py
- knox/settings.py
- setup.py
- tox.ini
Remove dependency to extra library which maybe require compiling.
Internal hashlib library has the same function. For default sha512 it does not require openssl. If openssl is available it is used for better performance.
Issue #199
~~This pr includes #225 because it does not work on old python 2.7.~~
> Use hashlib

- .codecov.yml
- .coveragerc
- .github/workflows/test.yml
- .pre-commit-config.yaml
- tests/tests.py
- tox.ini
This PR implements:
* A pre-commit hook that runs `isort` and `flake8`
* Code coverage reports and `codecov` WIP
> test: Set up pre-commit hooks and fix quality nits

- docs/auth.md
Move the file description outside the python code block to make it better readable.
> [doc] improve readability of example code

- .github/workflows/test.yml
- knox_project/settings.py
- setup.py
- tox.ini
* Django 4.1 has been released! https://docs.djangoproject.com/en/4.1/releases/4.1/
* Python 3.11 has been released!
* GitHub Actions: Deprecating save-state and set-output commands https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
*  Bump GH Actions versions
> Update gh actions; Add Django 4.1, Python 3.11

- knox/auth.py
- tests/tests.py
Not needed with Python 3 because it is default lib.
> Remove legacy code from Python 2

- CHANGELOG.md
Just a documentation addition according to and closes #266.
> fix(docs): add warning of migration to `4.2.0`

- docs/views.md
- knox/views.py
This pull request is a small change to enable customizing the response shape for the login and logout views by overriding a simple method.
This is useful in situations where for example the 204 responses in the logout views are undesirable (e.g. for clients that always assume that responses have a JSON body).
> Enable customizing login/logout responses

- knox/auth.py
- knox/crypto.py
- knox/models.py
- knox/settings.py
> feat: add typing

- .github/workflows/test.yml
- setup.py
- tox.ini
- Django 4.0 EOL since 01 Apr 2023.
- Django 4.1 EOL since 01 Dec 2023.
- 4.2 is new LTS.
- 5.0 is new current.
https://endoflife.date/django
> feat(ci): add current django and python to test

- knox/models.py
- tests/tests.py
Just some migrations to modern python.
> chore(migration): use f-string

- knox/auth.py
As titled, seems like the `TokenAuthentication` class already defined a method to retrieve the header, yet not utilized within the class itself.
ref: the related method
```python
def authenticate_header(self, request):
return knox_settings.AUTH_HEADER_PREFIX
```
[Similar technique](https://github.com/encode/django-rest-framework/blob/2797c0f216288bd7ca82e9e32e5f7d699bac74df/rest_framework/authentication.py#L180) has been done in `rest_framework` Token Authentication (though, using class attribute)
These changes allows the auth header to be overridden from the subclass without having to override the `authenticate()`  method (just for small auth prefix header changes) or meddling with global settings for `knox_settings.AUTH_HEADER_PREFIX` (because it might be used somewhere else within the …
> refactor(auth): Use `self.authenticate_header()` in `authenticate()` method to get auth header prefix

- knox/settings.py
`setting_changed` is actually from `django.core.signals`, and is re-exported from `django.test.signals`.
`django.test` takes 20-40ms to import, so not too much, but it's an easy win to avoid this import.
> Avoid importing `django.test` in main code

- tox.ini
Following on from the discussion in #344, this PR removes linting from the tox config to allow linting and testing to be run independently.
> Remove flake8 and isort from tox config

- CHANGELOG.md
This is to prepare relase in https://github.com/jazzband/django-rest-knox/pull/342
> add changelog for release

- CHANGELOG.md
I've increased the version to major, as this kind of a big change asks for one.
Fixes https://github.com/jazzband/django-rest-knox/issues/357
/cc @johnraz
> docs(changelog): bump to 5.0.0, add token warning

- knox/models.py
> chore: remove outdated super() call

- docker-run-tests.sh
Double quote to prevent globbing and word splitting. https://github.com/koalaman/shellcheck/wiki/SC2046
> fix(docker): possible path bug

- .github/workflows/test.yml
- .pre-commit-config.yaml
- knox_project/settings.py
- knox_project/urls.py
- setup.py
- tox.ini
This PR removes the following end-of-life versions of [Python](https://devguide.python.org/versions/) and [Django](https://jefftriplett.com/django-release-cycle/): 
- Python 3.6 - EOL: 23rd December 2021
- Python 3.7 - EOL: 27th June 2023
- Django 3.2 - EOL:  April 2024 
In addition to removing the EOL versions, the [Django upgrade pre-commit hook](https://github.com/adamchainz/django-upgrade) has also been added, and fixes are included in this PR. These changes relate to:
- The use of `USE_L10N`, which was deprecated in Django 4.0: https://github.com/adamchainz/django-upgrade?tab=readme-ov-file#use_l10n
- The use of `re_path`, which has been rewritten using the `path()` syntax added in Django 2.0: https://github.com/adamchainz/django-upgrade?tab=readme-ov-file#urls
> Remove EOL versions

- knox/views.py
- tests/tests.py
Fixes #280
Thanks to @pablomm for the code in the ticket
> Count non expiring tokens when determining if the limit is reached

- docs/auth.md
Came across this while trying to set the framework up. 
Not sure why but the given python2 syntax seems to error for my project citing `'super' object has no attribute 'post'`, migrating this to the python3 syntax seems to fix it.
> Use python3 syntax for super()
