CHANGELOG.rst, docs/auth.md, docs/changes.md, docs/settings.md, setup.py
fixes https://github.com/James1345/django-rest-knox/issues/25
=> Extending documentation regarding global usage

README.rst, docs/auth.md, docs/index.md, docs/installation.md, docs/settings.md, knox/views.py
- merge commits that are on master but not in develop
- remove references regarding not using urandom as it is no longer applicable from docs and readme
=> Remove reference re not using urandom from readme

CHANGELOG.rst, README.rst, docs/auth.md, docs/changes.md, docs/index.md, docs/installation.md, docs/settings.md, knox/migrations/0001_initial.py, knox/migrations/0002_auto_20150916_1425.py, knox/models.py, knox/views.py, setup.py
update models and migrations for Django 2.0 compatibility
=> update models and migrations for Django 2.0 compatibility

setup.py, tox.ini
=> Extend docs

knox/auth.py
=> Safer digests comparison

CHANGELOG.rst, docs/changes.md, knox/auth.py, setup.py
=> Fix py276 compability

tests/tests.py
This should wait for #90 to be merged
=> Simplified tests with setUp method

docs/auth.md
this aims to provide a example implementation for devs that aim to use Knox Token Authentication as their only authentication method.
=> Added a new section in auth docs

CHANGELOG.rst, docs/changes.md, knox/admin.py, setup.py
=> Add raw_id for user field in admin class

.travis.yml, CHANGELOG.rst, docs/changes.md, setup.py, tox.ini
for building it on django 2.1 and python 3.7 to ensure there are no problems. and if to fix them
=>  Add all metadata for django 2.1 

CHANGELOG.md, docs/changes.md
=> release notes 3.4

docs/settings.md
I might be misunderstanding something but I think this should be False instead of FALSE.
=> Change FALSE to False in code snippet

CHANGELOG.md, setup.py
Cherrypicked 4.1.0 commit from master.
=> Metadata for release 4.1.0

knox/admin.py
Just a tiny improvement for admin view.
=> add expiry column to admin view

.travis.yml, knox_project/settings.py, knox_project/urls.py, setup.py, tests/tests.py, tox.ini
update travis ci, setup.py, tox
add django 3.0 3.1
add python 3.8
remove django 1/2.0/2.1 
remove python 2.7
=> add new python and django to test

docs/auth.md, docs/urls.md, knox/urls.py
Just maintenance, should not have a real impact.
Fixes #237
=> fix deprecation of djangos url() #237

docs/settings.md
=> Right spelling DATETIME

knox/crypto.py
=> fix(docs): correct typo

docs/installation.md
=> Add missing dot in docs/installation.md

knox/models.py
This is just a quick solution the the problem described in issue #286
=> update AuthTokenManager to support custom values

knox_project/asgi.py, knox_project/settings.py, knox_project/urls.py, knox_project/views.py, knox_project/wsgi.py, manage.py
Started a new test project from scratch using newer Django defaults and migrated APIs over.
=> chore: Modernize example app
